//! Field-length quantisation for BM25 norms (Issue #555).
//!
//! Stores per-(doc, field) length as a single byte instead of a raw `u32`,
//! following the precedent set by Lucene's `SmallFloat` norms encoding and
//! Tantivy's `fieldnorm` table. Lengths below [`EXACT_LENGTH_BOUND`] are
//! represented exactly; above that, the table grows log-spaced (8 steps per
//! octave), trading precision for range the same way both reference
//! implementations do.
//!
//! The table is generated by [`build_norm_table`] from its recurrence
//! rather than hand-copied as a literal, so there is no risk of a
//! transcription error silently breaking monotonicity.
//!
//! ## The `.norms` segment part
//!
//! [`NormsBuilder`] accumulates flush-time field lengths and serializes them
//! into a `.norms` part, replacing the old `.lens` (per-doc, per-field
//! `string + u32`) and `.fstats` (a derivable fold of `.lens`) files.
//!
//! ```text
//! magic "NRMS"(4B) | version(2B, [1,0]) | codec_id(1B) | flags(1B)
//! doc_count(varint = N) | min_doc_id(u64) | max_doc_id(u64) | num_fields(varint)
//! -- slot map (only when flags bit 0 is unset, i.e. doc ids have gaps) --
//! delta(varint) x (N-1)     // ids[0] = min_doc_id; ids[i] = ids[i-1] + 1 + delta[i]
//! -- field directory (num_fields entries, in field-name order) --
//! { name(string) | present_count(varint) | sum_length(varint) | min_length(varint)
//!   | max_length(varint) | encoding(1B: 0=all present, 1=presence bitmap follows)
//!   | [presence bitmap: ceil(N/8) bytes, LSB-first] | norms: N bytes }
//! -- trailer: u32 CRC-32 checksum (StructWriter::close) --
//! ```
//!
//! `sum_length`/`present_count`/`min_length`/`max_length` are the *exact*,
//! pre-quantisation aggregates -- this is what lets `avg_length` (fed into
//! BM25's global length normalisation) stay bit-identical to what `.fstats`
//! used to report, instead of drifting from per-document quantisation noise.
//!
//! The presence bitmap (rather than a sentinel norm byte) is what keeps
//! "field absent" (`None`) distinguishable from "analyzed to zero tokens"
//! (`Some(0)`) -- `BM25Scorer::score` treats the two differently.
//!
//! Unlike [`super::doc_values`], fields are not lazily materialized: a
//! `.norms` file is already an order of magnitude smaller than the
//! `.lens`/`.fstats` pair it replaces (1 byte instead of a `String` key +
//! `u32` per (doc, field) held in memory), so the whole segment is read
//! once at [`NormsReader::load`] and cached by the caller.

use std::collections::BTreeMap;

use ahash::AHashMap;

use crate::error::{LaurusError, Result};
use crate::lexical::core::analyzed::AnalyzedDocument;
use crate::lexical::reader::FieldStats;
use crate::storage::Storage;
use crate::storage::StorageOutput;
use crate::storage::structured::{StructReader, StructWriter};
use crate::util::alloc_bounds::{checked_capacity, checked_len};

/// `.norms` segment part file extension.
const NORMS_EXTENSION: &str = ".norms";

const MAGIC: &[u8; 4] = b"NRMS";
const VERSION: [u8; 2] = [1, 0];
const CODEC_TANTIVY_TABLE_V1: u8 = 0;

/// Set in the header's `flags` byte when the segment's doc ids are
/// contiguous (`max_doc_id - min_doc_id + 1 == doc_count`), letting the
/// slot map be omitted entirely -- the common case for a fresh flush.
const FLAG_SLOT_MAP_CONTIGUOUS: u8 = 0b0000_0001;

const ENCODING_ALL_PRESENT: u8 = 0;
const ENCODING_PRESENCE_BITMAP: u8 = 1;

/// Minimum bytes one field's directory record can occupy on disk (an empty
/// name + four 1-byte varints + the encoding byte). Used to bound a
/// header-declared `num_fields` against the file's true size before it
/// drives an allocation, the same technique [`super::doc_values`] uses.
const MIN_FIELD_RECORD_SIZE: u64 = 1 + 1 + 1 + 1 + 1 + 1;

/// Lengths `0..EXACT_LENGTH_BOUND` map to themselves; beyond that the table
/// switches to log-spaced steps.
const EXACT_LENGTH_BOUND: u32 = 40;

/// Steps per octave in the log-spaced region (matches Tantivy's fieldnorm
/// table: the step size doubles every 8 entries).
const STEPS_PER_OCTAVE: u32 = 8;

const fn build_norm_table() -> [u32; 256] {
    let mut table = [0u32; 256];

    let mut i = 0usize;
    while i < EXACT_LENGTH_BOUND as usize {
        table[i] = i as u32;
        i += 1;
    }

    let mut value = EXACT_LENGTH_BOUND;
    let mut k = 0u32;
    while (EXACT_LENGTH_BOUND as usize + k as usize) < 256 {
        table[EXACT_LENGTH_BOUND as usize + k as usize] = value;
        let octave = k / STEPS_PER_OCTAVE;
        value += 2 * (1u32 << octave);
        k += 1;
    }

    table
}

/// `NORM_TABLE[b]` is the length represented by quantised byte `b`. Strictly
/// increasing (verified by [`tests::norm_table_is_strictly_increasing`]), so
/// `norm_to_length` is a plain index and `length_to_norm` can binary-search
/// it.
pub const NORM_TABLE: [u32; 256] = build_norm_table();

/// The largest length representable without saturating; longer fields all
/// quantise to `255`.
pub const MAX_NORM_LENGTH: u32 = NORM_TABLE[255];

/// Quantise a field length to a single byte.
///
/// Rounds down: `norm_to_length(length_to_norm(len)) <= len` always holds.
/// This direction (never overestimating) is what keeps the BM25 score bound
/// precomputed at flush time (`InvertedIndexWriter::compute_term_max_score_factor`)
/// a true upper bound once the reader substitutes the quantised length back
/// in — see the writer's `NormsBuilder` for why the two must agree.
pub fn length_to_norm(len: u32) -> u8 {
    if len < EXACT_LENGTH_BOUND {
        return len as u8;
    }
    match NORM_TABLE.binary_search(&len) {
        Ok(i) => i as u8,
        // `len >= EXACT_LENGTH_BOUND == NORM_TABLE[40]`, so the insertion
        // point is always >= 41; saturates to 255 when `len` exceeds
        // `MAX_NORM_LENGTH` (insertion point 256).
        Err(i) => (i - 1) as u8,
    }
}

/// Decode a quantised byte back to its representative length.
#[inline]
pub fn norm_to_length(norm: u8) -> u32 {
    NORM_TABLE[norm as usize]
}

/// `true` when a sorted, deduplicated doc-id slice has no gaps, i.e. the
/// contiguous slot-map fast path applies.
fn is_contiguous(sorted_doc_ids: &[u64]) -> bool {
    match (sorted_doc_ids.first(), sorted_doc_ids.last()) {
        (Some(&min), Some(&max)) => max - min + 1 == sorted_doc_ids.len() as u64,
        _ => true, // empty: vacuously contiguous, no slot map needed either way
    }
}

/// Accumulates flush-time field lengths for one segment and serializes them
/// into the `.norms` part.
///
/// A single instance must feed both the BM25 score-bound precomputation
/// (`InvertedIndexWriter::compute_term_max_score_factor`/
/// `compute_term_block_max`, via [`Self::decoded_length`]) and the on-disk
/// `.norms` write ([`Self::write_to`]). Splitting these into two independent
/// traversals of `buffered_docs` (as `.lens`/`.fstats` did) is what let the
/// score bound and the on-disk length silently diverge once quantisation is
/// introduced -- see the module docs.
pub(crate) struct NormsBuilder {
    /// Sorted, deduplicated doc ids covered by this segment.
    doc_ids: Vec<u64>,
    /// Field name -> (doc_id -> exact, pre-quantisation length). A
    /// `BTreeMap` so [`Self::write_to`] emits fields in a deterministic
    /// order regardless of insertion order (mirrors
    /// [`super::doc_values::DocValuesWriter`]'s rationale).
    fields: BTreeMap<String, AHashMap<u64, u32>>,
}

impl NormsBuilder {
    /// Build from the writer's buffered documents (fresh flush or merge
    /// reconstruction -- both hand this the same `&[(u64, AnalyzedDocument)]`
    /// shape `write_field_lengths` used to consume).
    pub(crate) fn from_buffered(docs: &[(u64, AnalyzedDocument)]) -> Self {
        let mut doc_ids: Vec<u64> = docs.iter().map(|(id, _)| *id).collect();
        doc_ids.sort_unstable();
        // The field promises deduplicated ids, and `write_to`'s delta
        // encoding underflows on a repeat. A buffer holds one entry per id
        // on every production path, but the public
        // `upsert_analyzed_document` can add a second (Issue #1210).
        doc_ids.dedup();

        let mut fields: BTreeMap<String, AHashMap<u64, u32>> = BTreeMap::new();
        for (doc_id, doc) in docs {
            for (field_name, &len) in &doc.field_lengths {
                fields
                    .entry(field_name.clone())
                    .or_default()
                    .insert(*doc_id, len);
            }
        }

        NormsBuilder { doc_ids, fields }
    }

    /// The segment's doc ids, sorted and deduplicated — the ids the
    /// `.norms` slot map records and the `.ids` part is written from, so the
    /// two can never disagree (Issue #1210).
    pub(crate) fn doc_ids(&self) -> &[u64] {
        &self.doc_ids
    }

    /// The decoded (quantised, then decoded back) length for `(doc_id,
    /// field)`. `None` when the document has no recorded length for this
    /// field.
    ///
    /// This -- not the exact length -- is what
    /// `compute_term_max_score_factor`/`compute_term_block_max` must use:
    /// the reader will substitute this same decoded value back in at search
    /// time, so anchoring the score bound to it keeps the bound valid (see
    /// [`length_to_norm`]'s round-down guarantee).
    pub(crate) fn decoded_length(&self, doc_id: u64, field: &str) -> Option<u32> {
        self.fields
            .get(field)?
            .get(&doc_id)
            .map(|&len| norm_to_length(length_to_norm(len)))
    }

    /// Exact average length for `field`, computed the same way
    /// `calculate_field_stats` did (`sum as f64 / count as f64`, narrowed to
    /// `f32` only after the division) so `avg_field_length` stays
    /// bit-identical to before #555. `0.0` when the field is absent from
    /// this segment, matching the pre-#555 fallback.
    pub(crate) fn avg_length_f32(&self, field: &str) -> f32 {
        let Some(lengths) = self.fields.get(field) else {
            return 0.0;
        };
        if lengths.is_empty() {
            return 0.0;
        }
        let sum: u64 = lengths.values().map(|&v| v as u64).sum();
        (sum as f64 / lengths.len() as f64) as f32
    }

    /// Serialize into the `.norms` format documented in the module docs.
    pub(crate) fn write_to<W: StorageOutput>(&self, writer: &mut StructWriter<W>) -> Result<()> {
        writer.write_raw(MAGIC)?;
        writer.write_raw(&VERSION)?;
        writer.write_u8(CODEC_TANTIVY_TABLE_V1)?;

        let contiguous = is_contiguous(&self.doc_ids);
        writer.write_u8(if contiguous {
            FLAG_SLOT_MAP_CONTIGUOUS
        } else {
            0
        })?;

        let doc_count = self.doc_ids.len() as u64;
        writer.write_varint(doc_count)?;
        writer.write_u64(self.doc_ids.first().copied().unwrap_or(0))?;
        writer.write_u64(self.doc_ids.last().copied().unwrap_or(0))?;
        writer.write_varint(self.fields.len() as u64)?;

        if !contiguous {
            for pair in self.doc_ids.windows(2) {
                let delta = pair[1] - pair[0] - 1;
                writer.write_varint(delta)?;
            }
        }

        let n = self.doc_ids.len();
        for (name, lengths) in &self.fields {
            let all_present = lengths.len() == n;
            let mut norms = vec![0u8; n];
            let mut presence = if all_present {
                None
            } else {
                Some(vec![0u8; n.div_ceil(8)])
            };
            let mut sum_length: u64 = 0;
            let mut min_length = u32::MAX;
            let mut max_length = 0u32;

            for (slot, doc_id) in self.doc_ids.iter().enumerate() {
                if let Some(&len) = lengths.get(doc_id) {
                    norms[slot] = length_to_norm(len);
                    sum_length += len as u64;
                    min_length = min_length.min(len);
                    max_length = max_length.max(len);
                    if let Some(bits) = presence.as_mut() {
                        bits[slot / 8] |= 1 << (slot % 8);
                    }
                }
            }
            if lengths.is_empty() {
                min_length = 0;
            }

            writer.write_string(name)?;
            writer.write_varint(lengths.len() as u64)?;
            writer.write_varint(sum_length)?;
            writer.write_varint(min_length as u64)?;
            writer.write_varint(max_length as u64)?;
            writer.write_u8(if presence.is_some() {
                ENCODING_PRESENCE_BITMAP
            } else {
                ENCODING_ALL_PRESENT
            })?;
            if let Some(bits) = &presence {
                writer.write_raw(bits)?;
            }
            writer.write_raw(&norms)?;
        }

        Ok(())
    }
}

/// Maps a segment's (possibly non-contiguous) doc ids to dense array slots.
#[derive(Debug)]
enum SlotMap {
    /// `doc_ids` form an unbroken range `min_doc_id..min_doc_id + count`.
    Contiguous { min_doc_id: u64, count: u32 },
    /// Sorted ascending doc ids, resolved by binary search.
    Sparse(Vec<u64>),
}

impl SlotMap {
    fn slot_of(&self, doc_id: u64) -> Option<usize> {
        match self {
            SlotMap::Contiguous { min_doc_id, count } => {
                let offset = doc_id.checked_sub(*min_doc_id)?;
                (offset < *count as u64).then_some(offset as usize)
            }
            SlotMap::Sparse(ids) => ids.binary_search(&doc_id).ok(),
        }
    }
}

/// One field's exact statistics and quantised norm column, as read from a
/// `.norms` file. Indices into `norms`/`presence` are slots resolved via the
/// enclosing [`NormsReader`]'s [`SlotMap`].
#[derive(Debug)]
struct NormsField {
    present_count: u64,
    sum_length: u64,
    min_length: u32,
    max_length: u32,
    /// `None` when every doc in the segment has this field (the common
    /// case); `Some(bitmap)` otherwise, LSB-first per byte.
    presence: Option<Box<[u8]>>,
    /// One quantised byte per slot, in slot order. Meaningless (left as
    /// `0`) at slots the presence bitmap marks absent.
    norms: Box<[u8]>,
}

/// Reader for the `.norms` segment part (Issue #555).
///
/// [`Self::load`] reads the whole file eagerly -- unlike
/// [`super::doc_values::DocValuesReader`], there is no per-field lazy
/// materialization here, because a `.norms` file is already close to the
/// smallest useful representation (module docs).
#[derive(Debug)]
pub(crate) struct NormsReader {
    slot_map: SlotMap,
    fields: AHashMap<String, NormsField>,
}

/// Read only the doc ids a segment's `.norms` part covers (Issue #1210).
///
/// The slot map is exactly the set of doc ids the segment holds, so a
/// segment written before the `.ids` part existed (Issue #1210) can still
/// answer "does this segment hold doc X?". Only the header and the slot map
/// are parsed; the field directory and the per-document norms are never
/// read. Unlike [`NormsReader::load`], `doc_count` is not bounded by one byte
/// per document: a contiguous `.norms` has no per-document bytes before its
/// fields, and a field-less one none at all (Issue #1213).
///
/// # Returns
///
/// `Ok(None)` when the segment has no `.norms` part (a pre-#555 segment).
///
/// # Errors
///
/// Returns an error when the part is unreadable, has a foreign magic or
/// version, or its slot map is inconsistent with its header.
pub(crate) fn read_doc_ids(
    storage: &dyn Storage,
    segment_id: &str,
) -> Result<Option<roaring::RoaringTreemap>> {
    let suffix = NORMS_EXTENSION.trim_start_matches('.');
    let Some(input) =
        crate::lexical::index::inverted::compound::open_part(storage, segment_id, suffix)?
    else {
        return Ok(None);
    };
    read_doc_ids_from(input).map(Some)
}

/// [`read_doc_ids`] over an already opened `.norms` input — for a caller
/// that holds the segment's own storage, such as a `SegmentReader` reading
/// through its compound facade (Issue #1211).
///
/// # Errors
///
/// Returns an error when the part has a foreign magic or version, or its
/// slot map is inconsistent with its header.
pub(crate) fn read_doc_ids_from<R: crate::storage::StorageInput>(
    input: R,
) -> Result<roaring::RoaringTreemap> {
    let mut reader = StructReader::new(input)?;
    let file_size = reader.size();

    let magic = reader.read_raw(MAGIC.len())?;
    if magic != MAGIC {
        return Err(LaurusError::index("Invalid .norms file format"));
    }
    let version = reader.read_raw(VERSION.len())?;
    if version[0] != VERSION[0] {
        return Err(LaurusError::index(format!(
            "Unsupported .norms version: {}.{}",
            version[0], version[1]
        )));
    }
    let _codec_id = reader.read_u8()?;
    let flags = reader.read_u8()?;
    let doc_count = reader.read_varint()?;
    let min_doc_id = reader.read_u64()?;
    let max_doc_id = reader.read_u64()?;
    let _num_fields = reader.read_varint()?;

    let mut ids = roaring::RoaringTreemap::new();
    if doc_count == 0 {
        return Ok(ids);
    }
    if flags & FLAG_SLOT_MAP_CONTIGUOUS != 0 {
        let end = min_doc_id.checked_add(doc_count).ok_or_else(|| {
            LaurusError::index("doc id overflow in .norms header — segment is corrupted")
        })?;
        ids.insert_range(min_doc_id..end);
    } else {
        // Each of the `doc_count - 1` deltas takes at least one byte.
        let available = file_size.saturating_sub(reader.position());
        checked_capacity((doc_count - 1) as usize, 1, available, "doc_count")?;
        ids.insert(min_doc_id);
        let mut prev = min_doc_id;
        for _ in 1..doc_count {
            let delta = reader.read_varint()?;
            let next = prev.checked_add(delta + 1).ok_or_else(|| {
                LaurusError::index("doc id overflow in .norms slot map — segment is corrupted")
            })?;
            ids.insert(next);
            prev = next;
        }
    }
    if ids.max() != Some(max_doc_id) {
        return Err(LaurusError::index(
            ".norms slot map does not end at the header's max_doc_id — segment is corrupted",
        ));
    }
    Ok(ids)
}

impl NormsReader {
    /// Load `{segment_id}.norms` from `storage`. `Ok(None)` means the file
    /// does not exist (a pre-#555 segment, or one with no indexed fields
    /// yet) -- not an error.
    pub(crate) fn load(storage: &dyn Storage, segment_id: &str) -> Result<Option<Self>> {
        let file_name = format!("{segment_id}{NORMS_EXTENSION}");
        let input = match storage.open_input(&file_name) {
            Ok(input) => input,
            Err(_) => return Ok(None),
        };
        let mut reader = StructReader::new(input)?;
        let file_size = reader.size();

        let magic = reader.read_raw(MAGIC.len())?;
        if magic != MAGIC {
            return Err(LaurusError::index("Invalid .norms file format"));
        }
        let version = reader.read_raw(VERSION.len())?;
        if version[0] != VERSION[0] {
            return Err(LaurusError::index(format!(
                "Unsupported .norms version: {}.{}",
                version[0], version[1]
            )));
        }
        let _codec_id = reader.read_u8()?;
        let flags = reader.read_u8()?;

        let doc_count = reader.read_varint()?;
        let available = file_size.saturating_sub(reader.position());
        let doc_count = checked_capacity(doc_count as usize, 1, available, "doc_count")? as u32;

        let min_doc_id = reader.read_u64()?;
        let _max_doc_id = reader.read_u64()?;

        let num_fields = reader.read_varint()?;
        let available = file_size.saturating_sub(reader.position());
        let num_fields = checked_capacity(
            num_fields as usize,
            MIN_FIELD_RECORD_SIZE,
            available,
            "num_fields",
        )?;

        let contiguous = flags & FLAG_SLOT_MAP_CONTIGUOUS != 0;
        let slot_map = if contiguous {
            SlotMap::Contiguous {
                min_doc_id,
                count: doc_count,
            }
        } else {
            let mut ids = Vec::with_capacity(doc_count as usize);
            if doc_count > 0 {
                ids.push(min_doc_id);
                let mut prev = min_doc_id;
                for _ in 1..doc_count {
                    let delta = reader.read_varint()?;
                    let next = prev.checked_add(delta + 1).ok_or_else(|| {
                        LaurusError::index(
                            "doc id overflow in .norms slot map — segment is corrupted",
                        )
                    })?;
                    ids.push(next);
                    prev = next;
                }
            }
            SlotMap::Sparse(ids)
        };

        let mut fields = AHashMap::new();
        for _ in 0..num_fields {
            let name = reader.read_string()?;
            let present_count = reader.read_varint()?;
            let sum_length = reader.read_varint()?;
            let min_length = reader.read_varint()? as u32;
            let max_length = reader.read_varint()? as u32;
            let encoding = reader.read_u8()?;

            let presence = if encoding == ENCODING_PRESENCE_BITMAP {
                let nbytes = (doc_count as usize).div_ceil(8);
                let available = file_size.saturating_sub(reader.position());
                let nbytes = checked_len(nbytes, available, "presence bitmap")?;
                Some(reader.read_raw(nbytes)?.into_boxed_slice())
            } else {
                None
            };

            let available = file_size.saturating_sub(reader.position());
            let norm_len = checked_len(doc_count as usize, available, "norm column")?;
            let norms = reader.read_raw(norm_len)?.into_boxed_slice();

            fields.insert(
                name,
                NormsField {
                    present_count,
                    sum_length,
                    min_length,
                    max_length,
                    presence,
                    norms,
                },
            );
        }

        Ok(Some(NormsReader { slot_map, fields }))
    }

    /// Quantised-then-decoded length for `(doc_id, field)`. `None` when the
    /// field has no `.norms` column in this segment, `doc_id` falls outside
    /// it, or the presence bitmap marks it absent -- callers must not
    /// conflate this with a recorded length of zero (`Some(0)`).
    pub(crate) fn field_length(&self, doc_id: u64, field: &str) -> Option<u32> {
        let f = self.fields.get(field)?;
        let slot = self.slot_map.slot_of(doc_id)?;
        let present = match &f.presence {
            None => true,
            Some(bits) => bits
                .get(slot / 8)
                .map(|b| (b >> (slot % 8)) & 1 == 1)
                .unwrap_or(false),
        };
        if !present {
            return None;
        }
        Some(norm_to_length(f.norms[slot]))
    }

    /// Exact field statistics for `field`, folded from the header's
    /// pre-quantisation aggregates (not from the quantised column) so
    /// `avg_length` matches what `.fstats` used to report.
    pub(crate) fn field_stats(&self, field: &str) -> Option<FieldStats> {
        let f = self.fields.get(field)?;
        let avg_length = if f.present_count > 0 {
            f.sum_length as f64 / f.present_count as f64
        } else {
            0.0
        };
        Some(FieldStats {
            field: field.to_string(),
            unique_terms: 0,
            total_terms: 0,
            doc_count: f.present_count,
            avg_length,
            min_length: f.min_length as u64,
            max_length: f.max_length as u64,
        })
    }

    /// All field names this `.norms` file recorded a length column for. A
    /// pure directory lookup, mirroring
    /// [`super::doc_values::DocValuesReader::field_names`] -- used by the
    /// merge engine (#1122) to reconstruct a length for a field that
    /// analyzed to zero tokens (and so left no term postings for
    /// `field_terms`-based enumeration to find).
    pub(crate) fn field_names(&self) -> Vec<String> {
        self.fields.keys().cloned().collect()
    }
}

#[cfg(test)]
mod format_tests {
    use super::*;
    use crate::storage::memory::{MemoryStorage, MemoryStorageConfig};

    fn doc(lengths: &[(&str, u32)]) -> AnalyzedDocument {
        let mut d = AnalyzedDocument::new();
        for &(field, len) in lengths {
            d.field_lengths.insert(field.to_string(), len);
        }
        d
    }

    /// Writes `builder` to `{segment_id}.norms` and reads it back.
    fn round_trip(
        storage: &MemoryStorage,
        segment_id: &str,
        builder: &NormsBuilder,
    ) -> NormsReader {
        let output = storage
            .create_output(&format!("{segment_id}{NORMS_EXTENSION}"))
            .unwrap();
        let mut writer = StructWriter::new(output);
        builder.write_to(&mut writer).unwrap();
        writer.close().unwrap();

        NormsReader::load(storage, segment_id).unwrap().unwrap()
    }

    #[test]
    fn round_trip_dense_contiguous_doc_ids() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![
            (0u64, doc(&[("title", 3), ("body", 120)])),
            (1u64, doc(&[("title", 5), ("body", 80)])),
            (2u64, doc(&[("title", 2), ("body", 200)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        let reader = round_trip(&storage, "seg_dense", &builder);

        assert_eq!(reader.field_length(0, "title"), Some(3));
        assert_eq!(reader.field_length(1, "title"), Some(5));
        assert_eq!(reader.field_length(2, "body"), Some(200));
        assert_eq!(reader.field_length(3, "title"), None); // doc doesn't exist
        assert_eq!(reader.field_length(0, "unknown"), None); // field doesn't exist
    }

    /// `read_doc_ids` recovers exactly the ids the slot map records, for a
    /// contiguous and a sparse segment (Issue #1210).
    #[test]
    fn read_doc_ids_recovers_the_slot_map() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let dense = vec![
            (4u64, doc(&[("title", 1)])),
            (5u64, doc(&[("title", 1)])),
            (6u64, doc(&[("title", 1)])),
        ];
        round_trip(&storage, "seg_dense", &NormsBuilder::from_buffered(&dense));
        let sparse = vec![
            (1u64, doc(&[("title", 1)])),
            (10u64, doc(&[("title", 1)])),
            (1u64 << 33, doc(&[("title", 1)])),
        ];
        round_trip(
            &storage,
            "seg_sparse",
            &NormsBuilder::from_buffered(&sparse),
        );

        let ids = |seg| {
            read_doc_ids(&storage, seg)
                .unwrap()
                .unwrap()
                .iter()
                .collect::<Vec<_>>()
        };
        assert_eq!(ids("seg_dense"), vec![4, 5, 6]);
        assert_eq!(ids("seg_sparse"), vec![1, 10, 1 << 33]);
        assert!(read_doc_ids(&storage, "missing").unwrap().is_none());
    }

    /// A contiguous `.norms` whose documents record no field lengths has no
    /// per-document bytes at all; `read_doc_ids` must not reject it for
    /// that, as `NormsReader::load` does past 21 documents (Issue #1213).
    #[test]
    fn read_doc_ids_accepts_a_large_field_less_segment() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs: Vec<_> = (0..30u64).map(|id| (id, doc(&[]))).collect();
        let builder = NormsBuilder::from_buffered(&docs);
        let output = storage.create_output("seg_bare.norms").unwrap();
        let mut writer = StructWriter::new(output);
        builder.write_to(&mut writer).unwrap();
        writer.close().unwrap();

        let ids = read_doc_ids(&storage, "seg_bare").unwrap().unwrap();
        assert_eq!(ids.len(), 30);
        assert_eq!((ids.min(), ids.max()), (Some(0), Some(29)));
    }

    /// A buffer holding one id twice records it once (Issue #1210): the
    /// field promised deduplicated ids, and the slot map's delta encoding
    /// underflowed on the repeat.
    #[test]
    fn duplicate_buffered_ids_are_recorded_once() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![
            (1u64, doc(&[("title", 3)])),
            (5u64, doc(&[("title", 4)])),
            (5u64, doc(&[("title", 6)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        assert_eq!(builder.doc_ids(), &[1, 5]);

        let reader = round_trip(&storage, "seg_dup", &builder);
        assert_eq!(reader.field_length(1, "title"), Some(3));
        assert!(reader.field_length(5, "title").is_some());
    }

    #[test]
    fn round_trip_sparse_doc_ids() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![
            (5u64, doc(&[("title", 3)])),
            (9u64, doc(&[("title", 7)])),
            (1000u64, doc(&[("title", 42)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        let reader = round_trip(&storage, "seg_sparse", &builder);

        assert_eq!(reader.field_length(5, "title"), Some(3));
        assert_eq!(reader.field_length(9, "title"), Some(7));
        assert_eq!(reader.field_length(1000, "title"), Some(42));
        // Doc ids that were never in the segment (including ones inside the
        // min..max span but not actually present) must resolve to nothing.
        assert_eq!(reader.field_length(6, "title"), None);
        assert_eq!(reader.field_length(4, "title"), None);
        assert_eq!(reader.field_length(1001, "title"), None);
    }

    #[test]
    fn round_trip_field_present_on_only_some_docs_uses_presence_bitmap() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![
            (0u64, doc(&[("title", 3), ("optional", 9)])),
            (1u64, doc(&[("title", 5)])), // no "optional"
            (2u64, doc(&[("title", 2), ("optional", 4)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        let reader = round_trip(&storage, "seg_ragged", &builder);

        assert_eq!(reader.field_length(0, "optional"), Some(9));
        assert_eq!(reader.field_length(1, "optional"), None);
        assert_eq!(reader.field_length(2, "optional"), Some(4));
        // A universally-present field must not pay for a bitmap it doesn't need.
        assert_eq!(reader.field_length(0, "title"), Some(3));
        assert_eq!(reader.field_length(1, "title"), Some(5));
    }

    #[test]
    fn zero_length_is_some_zero_not_none() {
        // Distinguishing "field analyzed to zero tokens" from "field absent"
        // is load-bearing for `BM25Scorer::score`'s `unwrap_or(avg)` fallback.
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![(0u64, doc(&[("title", 0)])), (1u64, doc(&[("title", 5)]))];
        let builder = NormsBuilder::from_buffered(&docs);
        let reader = round_trip(&storage, "seg_zero", &builder);

        assert_eq!(reader.field_length(0, "title"), Some(0));
        assert_ne!(reader.field_length(0, "title"), None);
    }

    #[test]
    fn header_stats_are_exact_pre_quantisation_values() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        // 39 is inside the exact window; nothing here is quantised, so the
        // header stats must match a plain integer fold exactly.
        let docs = vec![
            (0u64, doc(&[("body", 10)])),
            (1u64, doc(&[("body", 20)])),
            (2u64, doc(&[("body", 39)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        let reader = round_trip(&storage, "seg_stats", &builder);

        let stats = reader.field_stats("body").unwrap();
        assert_eq!(stats.doc_count, 3);
        assert_eq!(stats.min_length, 10);
        assert_eq!(stats.max_length, 39);
        assert!((stats.avg_length - (10.0 + 20.0 + 39.0) / 3.0).abs() < 1e-9);
    }

    #[test]
    fn header_stats_stay_exact_even_when_norms_are_quantised() {
        // Lengths chosen above EXACT_LENGTH_BOUND so the norm bytes lose
        // precision -- the header sums must not be derived from them.
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![
            (0u64, doc(&[("body", 1_000)])),
            (1u64, doc(&[("body", 50_000)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        let reader = round_trip(&storage, "seg_stats_quantised", &builder);

        let stats = reader.field_stats("body").unwrap();
        assert_eq!(stats.min_length, 1_000);
        assert_eq!(stats.max_length, 50_000);
        assert!((stats.avg_length - 25_500.0).abs() < 1e-9);

        // But the per-doc lookup is quantised, and quantised lengths must
        // never exceed the exact length that was written.
        assert!(reader.field_length(0, "body").unwrap() <= 1_000);
        assert!(reader.field_length(1, "body").unwrap() <= 50_000);
    }

    #[test]
    fn missing_norms_file_loads_as_none_not_an_error() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        assert!(
            NormsReader::load(&storage, "never_written")
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn rejects_bad_magic() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let mut output = storage.create_output("bad_magic.norms").unwrap();
        output.write_all(b"XXXX").unwrap();
        output.write_all(&VERSION).unwrap();
        output.close().unwrap();

        let err = NormsReader::load(&storage, "bad_magic").unwrap_err();
        match err {
            LaurusError::Index(msg) => assert!(msg.contains("Invalid .norms")),
            other => panic!("expected Index error, got {other:?}"),
        }
    }

    #[test]
    fn rejects_unsupported_major_version() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let mut output = storage.create_output("bad_version.norms").unwrap();
        output.write_all(MAGIC).unwrap();
        output.write_all(&[2u8, 0u8]).unwrap(); // major 2, doesn't exist yet
        output.close().unwrap();

        let err = NormsReader::load(&storage, "bad_version").unwrap_err();
        match err {
            LaurusError::Index(msg) => assert!(msg.contains("Unsupported .norms version")),
            other => panic!("expected Index error, got {other:?}"),
        }
    }

    #[test]
    fn rejects_a_doc_count_the_file_cannot_back() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let output = storage.create_output("corrupt_doc_count.norms").unwrap();
        let mut writer = StructWriter::new(output);
        writer.write_raw(MAGIC).unwrap();
        writer.write_raw(&VERSION).unwrap();
        writer.write_u8(CODEC_TANTIVY_TABLE_V1).unwrap();
        writer.write_u8(0).unwrap();
        writer.write_varint(u64::MAX).unwrap(); // impossible doc_count
        writer.close().unwrap();

        let err = NormsReader::load(&storage, "corrupt_doc_count").unwrap_err();
        match err {
            LaurusError::Index(msg) => assert!(msg.contains("corrupted")),
            other => panic!("expected Index error, got {other:?}"),
        }
    }

    #[test]
    fn rejects_a_num_fields_the_file_cannot_back() {
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let output = storage.create_output("corrupt_num_fields.norms").unwrap();
        let mut writer = StructWriter::new(output);
        writer.write_raw(MAGIC).unwrap();
        writer.write_raw(&VERSION).unwrap();
        writer.write_u8(CODEC_TANTIVY_TABLE_V1).unwrap();
        writer.write_u8(FLAG_SLOT_MAP_CONTIGUOUS).unwrap();
        writer.write_varint(1).unwrap(); // doc_count = 1
        writer.write_u64(0).unwrap(); // min_doc_id
        writer.write_u64(0).unwrap(); // max_doc_id
        writer.write_varint(u64::MAX).unwrap(); // impossible num_fields
        writer.close().unwrap();

        let err = NormsReader::load(&storage, "corrupt_num_fields").unwrap_err();
        match err {
            LaurusError::Index(msg) => assert!(msg.contains("corrupted")),
            other => panic!("expected Index error, got {other:?}"),
        }
    }

    #[test]
    fn decoded_length_never_exceeds_exact_length() {
        let docs = vec![
            (0u64, doc(&[("body", 1)])),
            (1u64, doc(&[("body", 1_000_000)])),
        ];
        let builder = NormsBuilder::from_buffered(&docs);
        assert_eq!(builder.decoded_length(0, "body"), Some(1));
        assert!(builder.decoded_length(1, "body").unwrap() <= 1_000_000);
        assert_eq!(builder.decoded_length(2, "body"), None);
        assert_eq!(builder.decoded_length(0, "missing"), None);
    }

    #[test]
    fn avg_length_f32_matches_exact_division() {
        let docs = vec![(0u64, doc(&[("body", 10)])), (1u64, doc(&[("body", 30)]))];
        let builder = NormsBuilder::from_buffered(&docs);
        assert_eq!(builder.avg_length_f32("body"), 20.0);
        assert_eq!(builder.avg_length_f32("missing"), 0.0);
    }

    #[test]
    fn no_lens_or_fstats_written_by_this_builder() {
        // NormsBuilder only ever touches its own `.norms` part -- guards
        // against a future refactor accidentally reintroducing a write to
        // the legacy files from this module.
        let storage = MemoryStorage::new(MemoryStorageConfig::default());
        let docs = vec![(0u64, doc(&[("title", 3)]))];
        let builder = NormsBuilder::from_buffered(&docs);
        let _ = round_trip(&storage, "seg_no_legacy", &builder);
        assert!(!storage.file_exists("seg_no_legacy.lens"));
        assert!(!storage.file_exists("seg_no_legacy.fstats"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn norm_table_is_strictly_increasing() {
        for i in 0..255 {
            assert!(
                NORM_TABLE[i] < NORM_TABLE[i + 1],
                "table not increasing at {i}: {} >= {}",
                NORM_TABLE[i],
                NORM_TABLE[i + 1]
            );
        }
    }

    #[test]
    fn norm_table_identity_window() {
        for (i, &value) in NORM_TABLE
            .iter()
            .enumerate()
            .take(EXACT_LENGTH_BOUND as usize)
        {
            assert_eq!(value, i as u32);
        }
    }

    #[test]
    fn norm_table_max_matches_closed_form() {
        // Regression guard against silently changing the recurrence.
        assert_eq!(NORM_TABLE[255], 2_013_265_944);
        assert_eq!(MAX_NORM_LENGTH, 2_013_265_944);
    }

    #[test]
    fn short_lengths_are_exact() {
        for len in 0..EXACT_LENGTH_BOUND {
            assert_eq!(norm_to_length(length_to_norm(len)), len);
        }
    }

    #[test]
    fn length_to_norm_is_monotone_non_decreasing() {
        let samples: Vec<u32> = (0..100_000).chain((0..256).map(|_| rand_like())).collect();
        let mut sorted = samples.clone();
        sorted.sort_unstable();
        let mut prev_norm = 0u8;
        let mut prev_len = 0u32;
        for &len in &sorted {
            let norm = length_to_norm(len);
            if len >= prev_len {
                assert!(
                    norm >= prev_norm,
                    "monotonicity violated: len {len} -> norm {norm}, prev len {prev_len} -> {prev_norm}"
                );
            }
            prev_len = len;
            prev_norm = norm;
        }
    }

    /// Deterministic stand-in for randomness so the test has no external
    /// dependency; only needs to hit a spread of large values.
    fn rand_like() -> u32 {
        use std::cell::Cell;
        thread_local! {
            static STATE: Cell<u32> = const { Cell::new(0x9E3779B9) };
        }
        STATE.with(|s| {
            let mut x = s.get();
            x ^= x << 13;
            x ^= x >> 17;
            x ^= x << 5;
            s.set(x);
            x
        })
    }

    #[test]
    fn decode_never_overestimates() {
        // BMW soundness lemma: the length substituted back in at search
        // time must never exceed the true length used when the score bound
        // was computed at flush time.
        for len in 0..200_000u32 {
            assert!(norm_to_length(length_to_norm(len)) <= len);
        }
        for _ in 0..10_000 {
            let len = rand_like();
            assert!(norm_to_length(length_to_norm(len)) <= len);
        }
        assert_eq!(norm_to_length(length_to_norm(u32::MAX)), MAX_NORM_LENGTH);
    }

    #[test]
    fn encode_is_idempotent_on_decoded() {
        // Merge-stability lemma: re-encoding an already-decoded length
        // reproduces the same byte, so quantisation drift does not
        // compound across repeated merges.
        for norm in 0..=255u8 {
            let decoded = norm_to_length(norm);
            assert_eq!(length_to_norm(decoded), norm);
        }
    }

    #[test]
    fn relative_error_within_one_eighth() {
        for len in EXACT_LENGTH_BOUND..500_000 {
            let decoded = norm_to_length(length_to_norm(len));
            let err = (len - decoded) as f64 / len as f64;
            assert!(err <= 0.125, "len={len} decoded={decoded} err={err}");
        }
    }

    #[test]
    fn saturates_at_u32_max_without_panicking() {
        assert_eq!(length_to_norm(u32::MAX), 255);
        assert_eq!(length_to_norm(MAX_NORM_LENGTH), 255);
        assert_eq!(length_to_norm(MAX_NORM_LENGTH + 1), 255);
    }

    #[test]
    fn zero_round_trips_to_zero() {
        assert_eq!(length_to_norm(0), 0);
        assert_eq!(norm_to_length(0), 0);
    }
}
