//! Field-length quantisation for BM25 norms (Issue #555).
//!
//! Stores per-(doc, field) length as a single byte instead of a raw `u32`,
//! following the precedent set by Lucene's `SmallFloat` norms encoding and
//! Tantivy's `fieldnorm` table. Lengths below [`EXACT_LENGTH_BOUND`] are
//! represented exactly; above that, the table grows log-spaced (8 steps per
//! octave), trading precision for range the same way both reference
//! implementations do.
//!
//! The table is generated by [`build_norm_table`] from its recurrence
//! rather than hand-copied as a literal, so there is no risk of a
//! transcription error silently breaking monotonicity.

/// Lengths `0..EXACT_LENGTH_BOUND` map to themselves; beyond that the table
/// switches to log-spaced steps.
const EXACT_LENGTH_BOUND: u32 = 40;

/// Steps per octave in the log-spaced region (matches Tantivy's fieldnorm
/// table: the step size doubles every 8 entries).
const STEPS_PER_OCTAVE: u32 = 8;

const fn build_norm_table() -> [u32; 256] {
    let mut table = [0u32; 256];

    let mut i = 0usize;
    while i < EXACT_LENGTH_BOUND as usize {
        table[i] = i as u32;
        i += 1;
    }

    let mut value = EXACT_LENGTH_BOUND;
    let mut k = 0u32;
    while (EXACT_LENGTH_BOUND as usize + k as usize) < 256 {
        table[EXACT_LENGTH_BOUND as usize + k as usize] = value;
        let octave = k / STEPS_PER_OCTAVE;
        value += 2 * (1u32 << octave);
        k += 1;
    }

    table
}

/// `NORM_TABLE[b]` is the length represented by quantised byte `b`. Strictly
/// increasing (verified by [`tests::norm_table_is_strictly_increasing`]), so
/// `norm_to_length` is a plain index and `length_to_norm` can binary-search
/// it.
pub const NORM_TABLE: [u32; 256] = build_norm_table();

/// The largest length representable without saturating; longer fields all
/// quantise to `255`.
pub const MAX_NORM_LENGTH: u32 = NORM_TABLE[255];

/// Quantise a field length to a single byte.
///
/// Rounds down: `norm_to_length(length_to_norm(len)) <= len` always holds.
/// This direction (never overestimating) is what keeps the BM25 score bound
/// precomputed at flush time (`InvertedIndexWriter::compute_term_max_score_factor`)
/// a true upper bound once the reader substitutes the quantised length back
/// in — see the writer's `NormsBuilder` for why the two must agree.
pub fn length_to_norm(len: u32) -> u8 {
    if len < EXACT_LENGTH_BOUND {
        return len as u8;
    }
    match NORM_TABLE.binary_search(&len) {
        Ok(i) => i as u8,
        // `len >= EXACT_LENGTH_BOUND == NORM_TABLE[40]`, so the insertion
        // point is always >= 41; saturates to 255 when `len` exceeds
        // `MAX_NORM_LENGTH` (insertion point 256).
        Err(i) => (i - 1) as u8,
    }
}

/// Decode a quantised byte back to its representative length.
#[inline]
pub fn norm_to_length(norm: u8) -> u32 {
    NORM_TABLE[norm as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn norm_table_is_strictly_increasing() {
        for i in 0..255 {
            assert!(
                NORM_TABLE[i] < NORM_TABLE[i + 1],
                "table not increasing at {i}: {} >= {}",
                NORM_TABLE[i],
                NORM_TABLE[i + 1]
            );
        }
    }

    #[test]
    fn norm_table_identity_window() {
        for i in 0..EXACT_LENGTH_BOUND as usize {
            assert_eq!(NORM_TABLE[i], i as u32);
        }
    }

    #[test]
    fn norm_table_max_matches_closed_form() {
        // Regression guard against silently changing the recurrence.
        assert_eq!(NORM_TABLE[255], 2_013_265_944);
        assert_eq!(MAX_NORM_LENGTH, 2_013_265_944);
    }

    #[test]
    fn short_lengths_are_exact() {
        for len in 0..EXACT_LENGTH_BOUND {
            assert_eq!(norm_to_length(length_to_norm(len)), len);
        }
    }

    #[test]
    fn length_to_norm_is_monotone_non_decreasing() {
        let samples: Vec<u32> = (0..100_000).chain((0..256).map(|_| rand_like())).collect();
        let mut sorted = samples.clone();
        sorted.sort_unstable();
        let mut prev_norm = 0u8;
        let mut prev_len = 0u32;
        for &len in &sorted {
            let norm = length_to_norm(len);
            if len >= prev_len {
                assert!(
                    norm >= prev_norm,
                    "monotonicity violated: len {len} -> norm {norm}, prev len {prev_len} -> {prev_norm}"
                );
            }
            prev_len = len;
            prev_norm = norm;
        }
    }

    /// Deterministic stand-in for randomness so the test has no external
    /// dependency; only needs to hit a spread of large values.
    fn rand_like() -> u32 {
        use std::cell::Cell;
        thread_local! {
            static STATE: Cell<u32> = const { Cell::new(0x9E3779B9) };
        }
        STATE.with(|s| {
            let mut x = s.get();
            x ^= x << 13;
            x ^= x >> 17;
            x ^= x << 5;
            s.set(x);
            x
        })
    }

    #[test]
    fn decode_never_overestimates() {
        // BMW soundness lemma: the length substituted back in at search
        // time must never exceed the true length used when the score bound
        // was computed at flush time.
        for len in 0..200_000u32 {
            assert!(norm_to_length(length_to_norm(len)) <= len);
        }
        for _ in 0..10_000 {
            let len = rand_like();
            assert!(norm_to_length(length_to_norm(len)) <= len);
        }
        assert!(norm_to_length(length_to_norm(u32::MAX)) <= u32::MAX);
    }

    #[test]
    fn encode_is_idempotent_on_decoded() {
        // Merge-stability lemma: re-encoding an already-decoded length
        // reproduces the same byte, so quantisation drift does not
        // compound across repeated merges.
        for norm in 0..=255u8 {
            let decoded = norm_to_length(norm);
            assert_eq!(length_to_norm(decoded), norm);
        }
    }

    #[test]
    fn relative_error_within_one_eighth() {
        for len in EXACT_LENGTH_BOUND..500_000 {
            let decoded = norm_to_length(length_to_norm(len));
            let err = (len - decoded) as f64 / len as f64;
            assert!(err <= 0.125, "len={len} decoded={decoded} err={err}");
        }
    }

    #[test]
    fn saturates_at_u32_max_without_panicking() {
        assert_eq!(length_to_norm(u32::MAX), 255);
        assert_eq!(length_to_norm(MAX_NORM_LENGTH), 255);
        assert_eq!(length_to_norm(MAX_NORM_LENGTH + 1), 255);
    }

    #[test]
    fn zero_round_trips_to_zero() {
        assert_eq!(length_to_norm(0), 0);
        assert_eq!(norm_to_length(0), 0);
    }
}
